import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NavAdmin from "@/components/backend/navbar";
import FootAdmin from "@/components/backend/footer";
import SideNav from "@/components/backend/sideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ToastContainer />
        <NavAdmin />
        <div className="flex flex-row">
          <div className="flex-1 min-h-[calc(100vh-125px)]">
            <SideNav />
          </div>
          <div className="flex-5 bg-amber-50">{children}</div>
        </div>

        <FootAdmin />
      </body>
    </html>
  );
}
